// Banco de dados estático das 10 questões oficiais da AQOI
const AQOI_QUESTION_BANK = [
    {
        id: 1,
        title: "CONDUTA_PENAL",
        text: "1° QUESTÃO - O coronel Pistache registrou sua licença no RCCSystem do dia 02 até 17 de abril. Contudo, após resolver suas pendências, registrou seu retorno no dia 11 de abril. Após seu retorno, observou que o tenente Labubu não estava apresentando presença no batalhão. Diante disso, no dia 18 de abril, o coronel decidiu rebaixar o tenente pelo crime de insuficiência para a patente, baseado na falta de quaisquer habilidades necessárias para um Oficial do Corpo Militar, utilizando como prova no requerimento apenas prints do perfil do militar, nos quais constava, reiteradas vezes, o status de 48 hours offline. Com base nas informações fornecidas, analise a ação do rebaixamento e a postagem do coronel, indicando se estão corretas ou incorretas e justificando sua resposta.",
        answer: "A atitude do coronel em rebaixar está correta, uma vez que este compensou 07 dias de atividade após retornar de sua licença de serviço. Entretanto, as provas utilizadas no rebaixamento estão incorretas. Em casos de rebaixamento de um militar por insuficiência para a patente, feito por um promotor que tenha compensado pelo menos 07 dias de licença, mas que ainda restem dias para compensar, deverá conter obrigatoriamente, como prova, depoimentos de superiores do policial rebaixado.",
        keywords: ["correta", "compensou", "07 dias", "licenca", "provas", "incorretas", "depoimentos de superiores", "reanimar", "insuficiencia"],
        timeDesktop: 180,
        timeMobile: 240
    },
    {
        id: 2,
        title: "CONDUTA_PENAL",
        text: "2° QUESTÃO - O aspirante Caio, inconformado por não ter sido promovido, utilizou-se de seu acesso às dependências por meio do setor de fiscalização de sua companhia para adentrar ao batalhão e fazer baderna com o uso de uma conta fake, identificando-se durante o ato. Diante disso, o capitão Antônio, membro da Repartição de Ações Interventivas e Ostensivas, exonerou o aspirante pelo crime de BADERNA. Contudo, o general Francisco afirmou que a conduta do capitão foi incorreta, sob o argumento de que ele não possui autoridade para aplicar tal punição sem autorização dos órgãos competentes. Além disso, diz que a situação não deveria ser enquadrada no crime mencionado. Diante disso, analise se o general Francisco está correto em suas afirmações, justificando sua resposta. Ademais, quanto à segunda afirmação, com base no princípio da especialidade, indique se o enquadramento está correto; caso contrário, aponte o crime adequado.",
        answer: "Em relação à primeira afirmação do general, está incorreta, uma vez que o capitão possui autoridade para aplicar a exoneração nos casos de baderna e/ou invasão, sobretudo por ser membro da Repartição de Ações Interventivas e Ostensivas. Ademais, quanto à segunda afirmação, está correto, visto que o crime de baderna não é o enquadramento adequado. Aplicando-se o princípio da especialidade, a conduta deve ser tipificada como utilização de fakes.",
        keywords: ["primeira", "incorreta", "autoridade", "exoneracao", "baderna", "invasao", "raio", "segunda", "correto", "especialidade", "fakes"],
        timeDesktop: 180,
        timeMobile: 240
    },
    {
        id: 3,
        title: "CONDUTA_PENAL",
        text: "3° QUESTÃO - Joãozinho iniciou a sua carreira como trainee em 2023, encerrando no mesmo como VIP, portador da Especialização Avançada e sem comprar nenhum cargo. Com isso, solicitou o passe de oficial reformado, sendo este aprovado. Em 2024 retornou ao Corpo Executivo, alcançando o posto de inspetor-geral e como não alcançou o cargo exigido para obter o passe, solicitou à Corregedoria em prol de sua carreira passada, sendo concedido. Por fim, no ano de 2025 retornou à instituição, mas dessa vez chegou até supervisor, solicitando novamente o passe de oficial reformado, que também foi aceito. Os pedidos de Joãozinho foram concedidos corretamente? Justifique. Além disso, fale quais requisitos um oficial do corpo executivo precisa ter para obter o passe de oficial reformado.",
        answer: "Não. Ele só poderá solicitar o seu passe em prol da carreira anterior uma única vez, sendo restrito a uma solicitação por cada conquista de reformado. Em relação aos requisitos, são: Ter se reformado no cargo de superintendente ou superior, desde que tenha iniciado como trainee ou sido reintegrado como analista, e não tenha efetuado compra de cargo até o posto em que se reformou; Ser portador da Especialização Avançada; Obter o reconhecimento como oficial reformado em segunda instância, mediante o envio de pedido à Corregedoria.",
        keywords: ["nao", "anterior", "unica vez", "requisitos", "superintendente", "trainee", "compra", "avancada", "corregedoria"],
        timeDesktop: 180,
        timeMobile: 240
    },
    {
        id: 4,
        title: "CONDUTA_PENAL",
        text: "4° QUESTÃO - O capitão Lucas presenciou, em uma chamada por voz, o marechal Marcos e a general Sofia planejando e promovendo o Aspirante a Oficial Pedro, amigo pessoal de ambos. No entanto, o aspirante havia sido recentemente avaliado com um desempenho abaixo do esperado, tanto documentalmente quanto em suas funções, possuindo pontos a serem aprimorados. Diante disso, Lucas relatou os fatos ao Comandante Ricardo, porém, utilizando apenas o argumento de ter escutado. O capitão agiu de forma correta? Justifique sua resposta, indicando possíveis crimes cometidos, a punição aplicável e, caso a conduta esteja incorreta, em quais circunstâncias ela poderia ser considerada adequada.",
        answer: "Não, pois o capitão precisaria de provas para acusar o marechal Marcos e a general Sofia. Como não apresentou nenhuma evidência, ele deve ser punido com uma advertência escrita por acusação sem provas. A acusação sem provas não configura crime nas seguintes circunstâncias: I — O levantamento de dados obtidos por testemunhas, uma vez que se trata da versão dos fatos apresentada por estas; II — A denúncia de um suspeito ao Setor de Inteligência, porquanto se trata de uma suposição baseada em determinados indícios.",
        keywords: ["nao", "provas", "advertencia escrita", "testemunhas", "inteligencia", "indicios"],
        timeDesktop: 150,
        timeMobile: 210
    },
    {
        id: 5,
        title: "CONDUTA_PENAL",
        text: "5° QUESTÃO - A marechal Virgínia, ao ser promovida ao cargo de líder da companhia dos Instrutores, passou a analisar as funções desempenhadas pelo ministério e identificou diversas infrações cometidas pela supervisora-geral e estagiária Ludmilla. Diante dessas irregularidades, no dia 04 de abril, foi aplicada a medida de rebaixamento da supervisora-geral dentro da companhia. No dia 12 de abril, a policial Ludmilla percebeu que ainda possuía acesso à conta do ministério da companhia (Google), sendo assim, insatisfeita com sua punição, resolveu entrar e apagar todos os backups da listagem de membros. Posteriormente, resolveu se desligar, retornando em uma nova carreira como soldado. Diante disso, responda: a) Analisando a situação apresentada, identifique e justifique possíveis enquadramentos em crimes decorrentes das ações da marechal Virgínia, na condição de líder da companhia, bem como indique as punições cabíveis. b) A policial Ludmilla seria punida em sua nova carreira? Justifique sua resposta com base nos termos de extinção de punibilidade.",
        answer: "a) A líder da companhia, marechal Virgínia, seria enquadrada no crime de conta comprometida, visto que é de sua responsabilidade modificar a senha das contas do grupo de tarefas, dentro do prazo de 72 horas, sempre que um indivíduo que anteriormente tinha acesso a elas perde a permissão para acessá-las. A punição ficará à critério do Setor de Inteligência. b) Sim. A extinção da punibilidade pelo conhecimento do crime quando o militar se encontrar em uma carreira diferente da do cometimento do crime, não se aplicará em fatos passíveis de exoneração por tempo indeterminado.",
        keywords: ["conta comprometida", "senha", "72 horas", "permissao", "inteligencia", "sim", "carreira diferente", "exonerao por tempo indeterminado"],
        timeDesktop: 180,
        timeMobile: 240
    },
    {
        id: 6,
        title: "CONDUTA_PENAL",
        text: "6° QUESTÃO - A capitão Pônei utilizou a ferramenta de alteração de nickname disponível na versão moderna do jogo, optando por modificar seu nome para Maria. Diante disso, solicitou ao general João que realizasse os procedimentos administrativos necessários para prosseguir com a alteração. O general, por sua vez, publicou o requerimento de transferência de conta, e, sem maiores instruções, dispensou a policial. Considerando o caso apresentado e o decurso de 48 horas desde a aprovação do requerimento de transferência, sem a adoção de quaisquer ações, responda: a) Com base no caso apresentado, analise a conduta do general, indicando e justificando, se cabível, o crime cometido e a sanção aplicável. b) Apresente as obrigações, incluindo os prazos, tanto do responsável quanto do requerente após a realização da transferência.",
        answer: "a) O general cometeu o crime de abandono de dever/negligência e deverá ser punido com advertência escrita, tendo em vista que deixou de prestar as orientações necessárias quanto aos procedimentos a serem adotados pela policial requerente após a efetivação da transferência. b) No prazo máximo de 24 horas após a transferência, é obrigação do responsável orientar o militar requerente acerca de suas responsabilidades. Quanto ao requerente, cabem as seguintes obrigações: realizar a alteração da TAG no prazo de até 48 horas; efetuar o preenchimento do formulário no tópico [FÓRUM] Pedido de Transferência de Nick em até 72 horas; e publicar o requerimento de transferência de conta nos grupos de tarefas também no prazo de até 72 horas.",
        keywords: ["negligencia", "advertencia escrita", "procedimentos", "24 horas", "responsabilidades", "tag", "48 horas", "transferencia de nick", "72 horas", "grupos de tarefas"],
        timeDesktop: 180,
        timeMobile: 240
    },
    {
        id: 7,
        title: "COMANDO_BATALHAO",
        text: "7° QUESTÃO - O Oficial da Guarda aplicou o comando “sentido” após a entrada de um marechal (maior patente presente) e, minutos depois, o marechal reentrou no quarto e o comando foi novamente dado. Durante o comando sentido, um comandante entrou, mas o Oficial da Guarda não realizou o repasse imediato, pois o marechal havia iniciado sua fala. Em outro momento, um policial solicita o comando sentido para realizar um anúncio, sem autorização do maior superior presente. Com base apenas nas informações dadas, analise as condutas apresentadas e identifique quais estão corretas ou incorretas, justificando cada uma.",
        answer: "A aplicação do comando “sentido” na reentrada do marechal é incorreta, uma vez que o Oficial da Guarda não se deve aplicá-lo nessa situação, salvo se houver requisição do próprio. Contudo, ainda nesse contexto, apesar de ter aplicado o comando, agiu corretamente ao não o repassar ao comandante em sua entrada, tendo em vista que o marechal iniciou sua fala. A solicitação do comando “sentido” para anúncio, sem autorização prévia, também é incorreta, pois o requerente deve solicitá-la com antecedência a um policial de maior patente ou cargo presente no batalhão.",
        keywords: ["reentrada", "incorreta", "salvo", "requisicao", "repasse", "iniciou sua fala", "anuncio", "antecedencia", "maior patente"],
        timeDesktop: 150,
        timeMobile: 210
    },
    {
        id: 8,
        title: "COMANDO_BATALHAO",
        text: "8° QUESTÃO - Analise as afirmativas a seguir, classificando-as como verdadeira ou falsa, justificando a(s) falsa(s): I. O Oficial da Guarda pode realizar a migração de batalhão sempre que julgar conveniente para melhorar a organização, independentemente da motivação. II. Caso o batalhão atinja 75 policiais, o Oficial da Guarda pode abrir outro batalhão desde que haja, no mínimo, 10 policiais disponíveis para deslocamento. III. Ao abrir um segundo batalhão, o Oficial da Guarda não precisa se preocupar com a lotação do batalhão principal, desde que ambos permaneçam com quantidade equilibrada de policiais. IV. A atividade de recrutamento pode ser realizada mesmo que o batalhão esteja abaixo do contingente mínimo exigido para outras atividades.",
        answer: "I. Falsa. A migração entre batalhões é proibida por motivos fúteis, sendo permitida apenas em situações específicas, como baixo ou alto contingente, falta de portadores de direitos ou emergências que inutilizem o funcionamento pleno do batalhão. II. Verdadeira. III. Falsa. Ao abrir outro batalhão, o Oficial da Guarda deve manter o controle do batalhão principal, guaranteeing que este não fique com menos de 60 policiais e realizando deslocamentos quando necessário. IV. Verdadeira.",
        keywords: ["i. falsa", "proibida", "futis", "ii. verdadeira", "iii. falsa", "batalhao principal", "60 policiais", "iv. verdadeira"],
        timeDesktop: 180,
        timeMobile: 240
    },
    {
        id: 9,
        title: "CONTROLE_EMERGENCIAL",
        text: "9° QUESTÃO - O capitão Diamante, membro do Comando de Segurança Institucional, estava na função de Oficial da Guarda e ocorrem as seguintes situações em sequência: I - Um supervisor com especialização básica e um sargento foram kickados do batalhão. Ao solicitar que enviassem a comprovação no tópico, os policiais informaram que não tiraram print. II - O subtenente Bijuteria foi mutado e perguntou ao capitão como deveria comprovar o mute. Depois da explicação e o devido registro da comprovação no tópico, o capitão printou o chooser e encaminhou os policiais com direitos ao corredor principal. III - Após os portadores retornarem do corredor, houve um ataque de movimentação de mobílias em grande escala, sendo assim, o capitão printou o chooser e encaminhou os policiais com direitos ao corredor principal. Considerando apenas os fatos ocorridos, analise as situações e identifique erros cometidos pelo capitão, bem como os procedimentos corretos a serem adotados em cada situação. Ademais, quanto à situação II, indique a orientação que deveria ser fornecida ao subtenente.",
        answer: "Em relação à situação I, antes da solicitação das comprovações, o capitão deveria ter acionado o procedimento básico. Além disso, devido aos alvos mencionados não terem registrado a comprovação, o capitão deveria instruir e orientar a registrarem em um futuro ataque. Em relação à situação II, o capitão errou ao acionar o procedimento intermediário, quando o correto seria a adoção do procedimento básico. Ademais, quanto à orientação ao subtenente mutado, deve ser informado que é necessário apresentar um print em tela cheia, contendo o aviso de mute, bem como realizar a devida postagem no tópico [CSI] Central de Comprovações. Em relação à situação III, agiu corretamente acionando o procedimento intermediário.",
        keywords: ["procedimento basico", "futuro ataque", "errou", "procedimento intermediario", "tela cheia", "aviso de mute", "central de comprovacoes", "corretamente"],
        timeDesktop: 180,
        timeMobile: 240
    },
    {
        id: 10,
        title: "CONTROLE_EMERGENCIAL",
        text: "10° QUESTÃO - Durante o comando, o Oficial da Guarda se depara com um ataque de flood, passando a aplicar o procedimento básico de gravidade 2, realizando mute e kick nos usuários mal-intencionados. No entanto, o ataque persiste de forma contínua e impossibilitando o controle da situação, o que leva o Oficial da Guarda a solicitar apoio dos portadores de direitos para conter os envolvidos. Após isso, o teleporte do corredor é movimentado ao saguão e o Oficial da Guarda reposiciona a mobília ao seu local original e questiona os portadores sobre a possível responsabilidade pelo ocorrido, sem obter resposta. Considerando que o Oficial da Guarda seja membro do Comando de Segurança Institucional, indique e descreva os procedimentos corretos a serem adotados nas situações apresentadas.",
        answer: "No primeiro caso, diante da continuidade do ataque de flood mesmo após o procedimento básico, o correto seria o acionamento do procedimento intermediário de gravidade 2, que consiste na utilização da ferramenta localizada nas preferências do quarto para silenciar todos. Após isso, deverá mutar e kickar os usuários mal-intencionados, controlando o ataque e desativando a ferramenta. No segundo caso, ao ocorrer a movimentação do teleporte com potencial de comprometer a segurança, o correto seria acionar o procedimento básico de gravidade 3, que consiste em printar e salvar toda a lista de usuários presentes no quarto por meio do comando :chooser, sem a necessidade de questionamento, devendo registrar a ocorrência no tópico.",
        keywords: ["procedimento intermediario", "silenciar todos", "mutar e kickar", "desativando", "movimentacao do teleporte", "gravidade 3", ":chooser", "questionamento", "registrar"],
        timeDesktop: 180,
        timeMobile: 240
    }
];

// Banco de dados dos 75 flashcards doutrinários
const AQOI_FLASHCARDS = [
    { q: "Qual a punição aplicada a um oficial que concede permissão para uma promoção sem verificar previamente os requisitos do promotor?", a: "Advertência escrita pelo crime de Abandono de Dever/Negligência." },
    { q: "Em que circunstância um Marechal em licença de serviço possui autonomia para aplicar punições administrativas legitimamente?", a: "Quando o militar ocupa o cargo de Corregedor." },
    { q: "Qual a sanção para um oficial que permanece em modo offline ou com visibilidade oculta após 24 horas da notificação inicial?", a: "Um rebaixamento a cada 24 horas além da perda de direitos, se aplicável." },
    { q: "No contexto do Plano de Controle Emergencial, qual a gravidade de um ataque caracterizado por flood constante de balões de fala por civis?", a: "Gravidade 2." },
    { q: "Qual o procedimento intermediário deve ser adotado em ataques de gravidade 3 no batalhão?", a: "Silenciar todos os usuários do quarto e encaminhar os portadores de direitos ao Corredor Principal." },
    { q: "Qual a punição mínima e máxima para o crime de Traição, como a infiltração em outras polícias?", a: "Demissão imediata, podendo chegar à exoneração." },
    { q: "Qual o prazo máximo para um promotor realizar o Diálogo Pós-Promoção (DPP) ou instrução de um subordinado?", a: "24 horas após a divulgação da promoção." },
    { q: "Qual a consequência para um oficial que realiza uma promoção durante o período de bloqueio das avaliações mensais?", a: "Advertência escrita por Abandono de Dever/Negligência e cancelamento do requerimento." },
    { q: "Como deve ser punido o militar que aceita um usuário fake em um grupo oficial sem a verificação adequada?", a: "Advertência escrita pelo crime de Abandono de Dever/Negligência." },
    { q: "Qual a punição para um oficial que registra uma permissão no RCCSystem entre 1 e 2 horas após a postagem do requerimento?", a: "Advertência escrita por Abandono de Dever/Negligência." },
    { q: "No crime de Utilização de Fakes, qual a punição para o primeiro grau (uso de conta secundária sem autobenefício)?", a: "Rebaixamento." },
    { q: "Qual o prazo máximo para um policial interpor recurso contra uma punição ou veredito?", a: "7 dias após a publicação ou homologação da decisão." },
    { q: "Qual a sanção para o militar que realiza a venda de cargos ou contratação de civis em modo offline?", a: "50 medalhas efetivas negativas por Abandono de Dever/Negligência." },
    { q: "Qual crime é configurado pela reprodução indevida de designs de BBCode ocultando os créditos autorais?", a: "Plágio." },
    { q: "Qual a punição prevista para o crime de Plágio em casos de reincidência?", a: "Rebaixamento, condicionado ao parecer final do Alto Comando Supremo." },
    { q: "Sob qual condição um oficial pode ser punido por não registrar a comprovação de um ataque de kick ou mute?", a: "Quando o oficial possui Especialização Intermediária ou superior." },
    { q: "Qual a punição para o crime de Falsificação de Informações em documentos oficiais?", a: "Advertência escrita, podendo chegar à demissão imediata." },
    { q: "Qual o procedimento obrigatório do Oficial da Guarda ao identificar a movimentação de uma mobília que impacta a segurança?", a: "Acionar imediatamente o procedimento básico e realizar o print do chooser." },
    { q: "Em que situação a migração de policiais para o Batalhão Auxiliar torna-se obrigatória?", a: "Quando o batalhão principal atinge 75 usuários e há pelo menos 10 policiais disponíveis para o novo quarto." },
    { q: "Qual a punição para o Oficial da Guarda que não posta o relatório de abertura ou fechamento no prazo de 30 minutos?", a: "Advertência escrita (para oficiais) ou 50 medalhas efetivas negativas (para praças)." },
    { q: "Qual o período de validade do Certificado de Qualificação (CQ) após o desligamento ou reforma do policial?", a: "1 ano." },
    { q: "Qual a sanção para um oficial que utiliza a ferramenta 'bloquear' do Habbo contra outro policial ativo?", a: "Advertência escrita por Abandono de Dever/Negligência." },
    { q: "Qual a punição para um oficial que pula de 5 a 6 linhas de um script oficial durante uma aplicação?", a: "Advertência escrita." },
    { q: "Em casos de ataques simultâneos de kick contra todos os operadores, qual ação deve ser tomada pelo Oficial da Guarda?", a: "Acionamento conjunto do procedimento básico e do procedimento intermediário." },
    { q: "Qual a punição para o militar que ameaça atacar as dependências da instituição (Crime Contra a Paz Pública)?", a: "Advertência verbal até a exoneração." },
    { q: "Qual o prazo para a Corregedoria proferir um veredito oficial após a instauração de um recurso em segunda instância?", a: "48 horas, com possível prorrogação de 24 horas por falta de quórum." },
    { q: "Qual a punição para um oficial que realiza migração entre batalhões por motivos fúteis ou sem respaldo documental?", a: "Advertência escrita por Abandono de Dever/Negligência." },
    { q: "Qual o requisito de lotação mínima para que o Batalhão Principal continue operando após a abertura do Auxiliar?", a: "60 militares." },
    { q: "Qual a punição para o crime de Conduta Imprópria, como a troca de nickname sem autorização?", a: "Advertência verbal até a exoneração." },
    { q: "Qual a sanção para um oficial que não realiza a postagem de uma punição por reincidência em até 24 horas?", a: "50 medalhas efetivas negativas por Abandono de Dever/Negligência." },
    { q: "Qual a punição para o crime de Obstrução à Justiça em casos de mentiras durante processos investigativos?", a: "Advertência escrita até a exoneração por tempo indeterminado." },
    { q: "Como deve ser punida a acusação de um crime contra outrem sem a apresentação de evidências (Acusação sem Provas)?", a: "Advertência escrita até a demissão." },
    { q: "Qual a punição para o crime de Abuso de Poder, como o uso do cargo para benefício próprio?", a: "50 medalhas efetivas negativas até a demissão." },
    { q: "Qual a sanção para o oficial que cancela uma permissão registrada no RCCSystem como justificativa para cancelar um requerimento aprovado?", a: "Advertência escrita por Abandono de Dever/Negligência." },
    { q: "Em que prazo um requerimento negado pelo CRH deve ser repostado para manter a validade da permissão original?", a: "24 horas." },
    { q: "Qual a punição para o crime de Desrespeito e Insubordinação contra superiores?", a: "Advertência verbal até a exoneração." },
    { q: "Qual a sanção para o oficial que realiza promoção sem confirmar a disponibilidade da vaga ou ignorar requerimentos pendentes?", a: "Advertência escrita por Abandono de Dever/Negligência." },
    { q: "Qual o prazo para um oficial notificar o promotor original sobre o cancelamento de um requerimento de promoção?", a: "24 horas após o ato." },
    { q: "Qual a punição para o crime de Nepotismo (favorecimento por laços de amizade ou familiares)?", a: "Rebaixamento, podendo chegar à exoneração." },
    { q: "Em que condição a ocultação de créditos de um autor de projetos é permitida?", a: "Quando o autor é punido com exoneração por tempo indeterminado." },
    { q: "Qual o procedimento do Oficial da Guarda em casos de manutenção do Habbo Hotel com aviso prévio de 3 minutos?", a: "Realizar imediatamente os procedimentos de fechamento do batalhão." },
    { q: "Qual a sanção para o oficial que concede uma especialização sem verificar os requisitos exigidos?", a: "Advertência escrita por Abandono de Dever/Negligência." },
    { q: "No Plano de Controle Emergencial, quem possui autoridade exclusiva para acionar o procedimento intermediário?", a: "Membros do Comando de Segurança Institucional (CSI)." },
    { q: "Qual a punição para um oficial que utiliza direitos de forma petulante sem necessidade ou consentimento?", a: "50 medalhas efetivas negativas e perda de direitos." },
    { q: "Qual a punição para o crime de Quebra de Sigilo, como o vazamento de scripts de aulas?", a: "Advertência escrita até a exoneração." },
    { q: "No caso de reincidência de três rebaixamentos pelo mesmo crime em dois meses, qual a punição final?", a: "Demissão." },
    { q: "Qual a punição para o crime de Camuflagem de IP em casos mais graves?", a: "Exoneração de 3 meses." },
    { q: "Qual a sanção para o oficial que negligencia a aplicação de uma punição prevista nos documentos?", a: "Advertência verbal até o rebaixamento imediato." },
    { q: "Qual a punição para o crime de Utilização Indevida de Canais Externos, como ofensas no RCCSystem?", a: "Rebaixamento imediato até a exoneração." },
    { q: "Qual a consequência para o militar que comete o crime de Autopromoção falsificando sua própria patente?", a: "Demissão imediata até a exoneração de 1 mês." },
    { q: "Qual a sanção para o oficial que deixa de responder à avaliação mensal da Diretoria sem estar em licença?", a: "Advertência escrita por Abandono de Dever/Negligência." },
    { q: "Em que prazo uma sindicância relativa aos resultados da avaliação mensal deve ser protocolada?", a: "72 horas corridas após a divulgação do resultado." },
    { q: "Qual a punição para o avaliador que deixa de avaliar obrigatoriamente um executivo de seu turno primário?", a: "50 medalhas efetivas negativas por cada executivo não avaliado." },
    { q: "Qual o crime configurado pelo compartilhamento de senhas do System ou Google Drive da RCC?", a: "Conta Comprometida." },
    { q: "Qual a punição para o crime de Conta Comprometida quando o militar ainda não concluiu a Aula de Segurança (SEG)?", a: "Advertência verbal." },
    { q: "Qual a sanção para o militar que não cumpre as metas estabelecidas na subcompanhia Organizadores de Rondas?", a: "Punição interna de Abandono de Dever/Negligência (Advertência interna até Expulsão)." },
    { q: "Qual a punição para o crime de Baderna, como atrapalhar as atividades rotineiras da instituição?", a: "Demissão imediata até a exoneração de 3 meses." },
    { q: "Qual a sanção para o crime de Invasão em casos de entrada em local restrito sem autorização?", a: "Rebaixamento imediato até a exoneração de 3 meses." },
    { q: "Como é punido o crime de Ataque às estruturas da RCC em casos gravosos?", a: "Exoneração por tempo indeterminado." },
    { q: "Qual a punição para o crime de Corrupção ou Estelionato contra a instituição?", a: "Exoneração de 1 mês até exoneração por tempo indeterminado." },
    { q: "No contexto da PMJ, qual a frequência de aplicação da Avaliação de Qualificação do Oficialato Intermediário (AQOI)?", a: "A cada 14 dias." },
    { q: "Qual o comando obrigatório a ser dado pelo Oficial da Guarda quando um ex-Comandante Supremo com medalha de honra entra no batalhão?", a: "Continência (após o comando Sentido)." },
    { q: "Qual a punição para o oficial que realiza o fechamento de um batalhão para abrir outro por interesse pessoal?", a: "Advertência escrita por Abandono de Dever/Negligência." },
    { q: "Qual a sanção para o militar que ultrapassa 89 dias offline no RCCSystem sem Especialização Intermediária?", a: "Retirada do sistema por inatividade." },
    { q: "Qual a punição para um oficial que posta uma fiscalização de listagem sem pertencer à Companhia dos Supervisores?", a: "Advertência escrita pelo crime de Abandono de Dever/Negligência." },
    { q: "Qual a sanção aplicada ao militar que não quita a dívida de uma compra de cargo na data prevista?", a: "Exoneração de 1 mês até exoneração por tempo indeterminado." },
    { q: "No caso de um oficial que cai da conexão durante a abertura do batalhão, o que deve ser anexado ao relatório?", a: "O print da mensagem de queda de conexão dada pelo Habbo juntamente com as demais capturas possíveis." },
    { q: "Qual a punição para o crime de Insuficiência Para a Patente ou Cargo (ineficiência na companhia)?", a: "Regresso de especialização até o rebaixamento imediato." },
    { q: "Como deve ser punido o oficial que não encaminha o print do chooser ao Setor de Inteligência após um ataque total (Gravidade 4)?", a: "Advertência escrita por Abandono de Dever/Negligência." },
    { q: "Qual a punição para o membro da liderança da subcompanhia que não comunica formalmente uma punição ao envolvido por MP?", a: "50 medalhas efetivas negativas por Abandono de Dever/Negligência." },
    { q: "Qual o crime configurado pela mentira dita a um superior para negar uma ofensa comprovada por prints?", a: "Conduta Imprópria." },
    { q: "Sob qual princípio jurídico a aplicação de um crime mais específico prevalece sobre um menos específico em uma mesma conduta?", a: "Princípio da Especialidade." },
    { q: "Qual a punição para o oficial que avalia negligentemente um subordinado com comentários genéricos em todas as áreas?", a: "Advertência verbal até o rebaixamento, conforme a gravidade." },
    { q: "Qual a sanção para o oficial que concede permissão para uma exoneração sem possuir Especialização Básica ou integrar o Setor de Inteligência?", a: "Rebaixamento imediato, conforme o Anexo I do CPM." },
    { q: "Em que prazo a Corregedoria deve analisar e votar um recurso formal após o recebimento?", a: "48 horas." }
];
